Repository team-foxploit/FoxLearn, pull requests merged in 2019-01, with the labels that each got.

#7 sign up ui v1.0
  client/package-lock.json
  client/package.json
  client/src/components/auth/SignUp.js
  client/src/components/auth/styles.css
  client/src/components/images/bg-img-signup.jpg
Labels: Front-end

#8 Sidebar UI
  client/src/App.js
  client/src/components/auth/SignUp.js
  client/src/components/auth/styles.css
  client/src/components/dashboard/Dashboard.js
  client/src/components/dashboard/Sidebar.css
  client/src/components/dashboard/Sidebar.js
  client/src/components/dashboard/Wall.js
  client/src/components/dashboard/styles.css
  client/src/components/footer/footer.js
  client/src/components/images/download.png
  client/src/components/layout/Dashboard.css
  client/src/components/layout/Navbar.js
  client/src/components/layout/SideNavBar.js
Labels: Front-end, enhancement

#11 After Merge | New Branch Deleted
  client/src/App.js
  client/src/components/auth/SignLanding.js
  client/src/components/auth/SignUp.js
  client/src/components/dashboard/Dashboard.js
  client/src/components/dashboard/Sidebar.js
  client/src/components/dashboard/Wall.js
  client/src/components/layout/Home.js
  client/src/components/layout/MainNavbar.js
  client/src/components/layout/SignedInLinks.js
  client/src/components/layout/SignedInNavabr.js
  server.js
Labels: enhancement

#12 Landing Page
  client/src/components/auth/SignIn.js
  client/src/components/auth/styles.css
  client/src/components/images/parallax/1.jpg
  client/src/components/images/parallax/2.jpg
  client/src/components/images/parallax/3.jpg
  client/src/components/images/slider/1.jpg
  client/src/components/images/slider/2.jpg
  client/src/components/images/slider/3.jpg
  client/src/components/images/slider/4.jpg
  client/src/components/layout/Home.js
  package-lock.json
  package.json
Labels: Front-end

#13 Quiz card and Subject Card
  client/src/App.js
  client/src/components/auth/SignIn.js
  client/src/components/images/subject/chem.png
  client/src/components/images/subject/geo.png
  client/src/components/images/subject/his.jpg
  client/src/components/images/subject/it.jpg
  client/src/components/images/subject/phy.jpg
  client/src/components/images/subject/web.jpg
  client/src/components/quizzes/Quiz.js
  client/src/components/quizzes/Subjects.js
  client/src/components/quizzes/styles.css
Labels: Front-end

#14 UI updates
  client/public/favicon.ico
  client/src/components/auth/SignIn.js
  client/src/components/auth/SignLanding.js
  client/src/components/auth/SignUp.js
  client/src/components/auth/styles.css
  client/src/components/quizzes/Quiz.js
  client/src/components/quizzes/Subjects.js
Labels: enhancement

#16 SignUp page | Form validation fianalized
  src/components/auth/SignUp.js
Labels: enhancement

#17 Student History Page
  package-lock.json
  package.json
  src/App.js
  src/components/dashboard/History.js
  src/components/dashboard/History_teacher.js
  src/components/quizzes/CreateQuiz.js
Labels: Front-end, enhancement

#18 UI updates
  src/App.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/Sidebar.css
  src/components/dashboard/Sidebar.js
  src/components/dashboard/Wall.js
  src/components/dashboard/styles.css
  src/components/quizzes/CreateQuiz.js
  src/components/quizzes/Quiz.js
  src/components/quizzes/Subjects.js
Labels: enhancement

#22 Update
  src/components/auth/SignLanding.js
  src/components/auth/SignUp.js
  src/components/quizzes/QuizCard.js
Labels: Front-end, enhancement
